### ISSUE TITLE
Poor alignment of 'Add' button

### ISSUE THREAD

**Issue by 1to5pc** [SadeveM/To-do-Application#3]
![image](https://github.com/user-attachments/assets/267e32c5-12f7-47be-bcb9-d39c17868837)

**Comment by SadeveM** [comment]
![Screenshot 2024-10-22 160624](https://github.com/user-attachments/assets/c62d6810-da04-40d9-8169-ac4cb20f7aa8)

This issue isn't visible from my end, which device and browser are you using?

**Comment by 1to5pc** [comment]
Firefox 131.0.3 (64-bit) Linux

**Comment by SadeveM** [comment]
I addressed into this issue and hopefully it should be fixed, do provide your feedback, Thank you!

**Comment by senhas-rgb** [comment]
@SadeveM Please close the issue if its solved
