### ISSUE TITLE
Poor mobile support

### ISSUE THREAD

**Issue by 1to5pc** [SadeveM/To-do-Application#4]
![image](https://github.com/user-attachments/assets/686141f4-555e-4809-a677-540f355e890b)
The website has poor handling on mobile devices as the site does not resize according to the size of the screen.
![image](https://github.com/user-attachments/assets/1cc020bd-2f6d-4f77-98b7-017e37b7b097)
The site does not prevent the user scrolling down below the gradient.

**Comment by SadeveM** [comment]
Added simple mobile support to the website, do provide your experience with the website, thank you for presenting the issue.

**Comment by senhas-rgb** [comment]
@SadeveM Please close the issue if its solved.
